spring.application.name=springaidemo
spring.ai.stabilityai.api-key=abcdefghijklmnopq
spring.ai.stabilityai.image.options.model=sd3
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=tinyllama
